trigger:
  - main
  
  resources:
  - repo: self
  
  variables:
    dockerRegistryServiceConnection: 'e558d8c0-ffc1-40a0-8730-98efef5f770c'
  
  stages:
  - stage: Build
    displayName: Build and Push
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          repository: 'backend'
          dockerfile: 'backend/docker/backend.Dockerfile'
          buildContext: 'backend/src/backend_package'
          containerRegistry: 'personalsite.azurecr.io'
          tags: |
            $(Build.BuildId)
            latest
  