trigger:
  branches:
    include:
    - main
  paths:
    include:
    - backend/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'e558d8c0-ffc1-40a0-8730-98efef5f770c'
  imageRepository: 'backend'
  containerRegistry: 'personalsite.azurecr.io'
  dockerfilePath: 'backend/docker/backend.Dockerfile'
  dockerContextPath: 'backend/src/backend_package'

stages:
- stage: Build
  displayName: Build and Push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(dockerContextPath)
        arguments: --build-arg TELEMETRY_KEY=$(APP_INSIGHTS_KEY)
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(Build.BuildId)
          latest