trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'e558d8c0-ffc1-40a0-8730-98efef5f770c'

stages:
- stage: Build
  displayName: Build and Push
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: 'frontend'
        dockerfile: 'frontend/docker/frontend.Dockerfile'
        buildContext: 'frontend/app'
        containerRegistry: 'personalsite.azurecr.io'
        tags: |
          $(Build.BuildId)
          latest
