[tool.poetry]
authors = ["Chris Gregory <christopher.b.gregory@gmail.com>"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
]
description = "Personal website SDK"
keywords = ["personal", "website", "sdk", "python", "tools"]
license = "Apache Software License"
name = "chris"
readme = "README.md"
repository = "https://github.com/gregorybchris/personal-website"
version = "1.1.0"

[[tool.poetry.packages]]
include = "chris"

[tool.poetry.dependencies]
click = "^8.1.7"
fastapi = "^0.109.2"
httpx = "^0.26.0"
jsonvl = "^0.5.0"
pandas = "^2.2.0"
pydantic = "^2.6.0"
python = ">=3.11"
uvicorn = { version = "^0.27.0", extras = ["standard"] }

[tool.poetry.scripts]
cgme = "chris.cli.cli:main"

[tool.poetry.group.dev.dependencies]
covcheck = { version = "^0.4.3", extras = ["toml"] }
mypy = "^1.8.0"
pytest = "^8.0.0"
ruff = "^0.5.0"
pytest-cov = "^4.1.0"
semver = "^3.0.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.covcheck]
branch = 50.0
line = 50.0

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 120
src = ["chris"]

[tool.ruff.lint]
ignore = ["D100", "D104", "FIX002", "TD003"]
select = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C4",
  "E",
  "EM",
  "ERA",
  "F",
  "FIX",
  "G",
  "I",
  "ICN",
  "ISC",
  "LOG",
  "N",
  "PL",
  "PT",
  "PTH",
  "PLR",
  "RET",
  "RUF",
  "SIM",
  "SLF",
  "T20",
  "TCH",
  "TD",
  "TID",
  "W",
]

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
"**/*.py" = ["G004", "EM101", "EM102", "TD002"]
"**/tests/**/*.py" = ["SLF", "PLR2004", "PT013"]
"chris/validation/validate.py" = ["T201"]
"chris/utilities/generate_uuid.py" = ["T201"]
