[tool.poetry]
authors = ["Chris Gregory <christopher.b.gregory@gmail.com>"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Software Development",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
]
description = "Personal website SDK"
keywords = ["personal", "website", "sdk", "python", "tools"]
license = "Apache Software License"
name = "chris"
readme = "README.md"
repository = "https://github.com/gregorybchris/personal-website"
version = "1.0.0"

[[tool.poetry.packages]]
include = "chris"

[tool.poetry.dependencies]
fastapi = "^0.88.0"
gunicorn = "^20.1.0"
jsonvl = "^0.5.0"
pandas = "^1.5.2"
pydantic = "^1.10.2"
python = ">=3.8"
uvicorn = { version = "^0.20.0", extras = ["standard"] }
click = "^8.1.3"
httpx = "^0.23.1"

[tool.poetry.scripts]
cgme = "chris.cli.main:cli"

[tool.poetry.group.dev.dependencies]
covcheck = "^0.4.2"
flake8 = "^4.0.1"
mypy = "^0.960"
pydocstyle = "^6.1.1"
pylint = "^2.15.8"
pyproject-flake8 = "^0.0.1a2"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
semver = "^2.13.0"
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.covcheck]
branch = 42.0
line = 75.0

[tool.flake8]
ignore = ""           # Required to disable default ignores
max-line-length = 120

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pylint.basic]
good-names = ["f", "h", "i", "j", "k", "m", "n", "w", "x", "xs", "y"]
notes = ["FIXME"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.master]
extension-pkg-allow-list = ["pydantic"]

[tool.pylint.messages_control]
disable = [
  "logging-fstring-interpolation",
  "unspecified-encoding",
  "missing-docstring",
  "wrong-import-order",
  "duplicate-code",
  "too-few-public-methods",
]

[tool.pylint.reports]
output-format = "colorized"

[tool.yapf]
based_on_style = "pep8"
column_limit = 120
indent_width = 4
