name: API CI

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/ci-api.yaml
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/ci-api.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python 3.13 Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.17
          enable-cache: true
          cache-local-path: ~/.cache/uv
          cache-dependency-glob: backend/pyproject.toml

      - name: Install package
        run: uv sync --all-extras --dev

      - name: Run ruff
        shell: bash
        run: |
          uv run ruff check .
          uv run ruff format . --check
        working-directory: backend

      - name: Run mypy
        shell: bash
        run: |
          uv run mypy src --config pyproject.toml
        working-directory: backend

      - name: Run pytest
        shell: bash
        run: |
          uv run pytest tests -n auto --cov=src --cov-report=html --cov-report=xml --cov-branch --log-cli-level=INFO
        working-directory: backend

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-html
          path: backend/htmlcov

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-xml
          path: backend/coverage.xml

      - name: Run covcheck
        shell: bash
        run: |
          uv run covcheck coverage.xml --config pyproject.toml
        working-directory: backend
