name: API CI

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/ci-api.yaml
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/ci-api.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python 3.12 Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install poetry
          if [ -d /poetryenvs ]; then rm -rf ~/poetryenvs; fi
          poetry config virtualenvs.path ~/poetryenvs
          poetry install
        working-directory: backend

      - name: Run ruff check
        run: |
          poetry run ruff check .
          poetry run ruff format . --check
        working-directory: backend

      - name: Run mypy
        run: |
          poetry run mypy chris --config pyproject.toml
          poetry run mypy tests --config pyproject.toml
        working-directory: backend

      - name: Run pytest
        run: |
          poetry run pytest tests --cov=chris --cov-report=html --cov-report=xml --cov-branch
        working-directory: backend

      - name: Upload HTML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov

      - name: Upload XML Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: backend/coverage.xml

      - name: Check Coverage
        run: |
          poetry run covcheck coverage.xml --config pyproject.toml
        working-directory: backend
