name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - chris/overhaul
    paths:
      - frontend/**
      - .github/workflows/deploy-frontend.yaml

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-frontend:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --remote-only
        working-directory: frontend
